"""API token

Revision ID: d095f0bf262d
Revises: cb013586de1f
Create Date: 2020-05-17 15:24:29.935395

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd095f0bf262d'
down_revision = 'cb013586de1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('api_token', sa.String(length=64), nullable=True))
    op.create_index(op.f('ix_user_api_token'), 'user', ['api_token'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_api_token'), table_name='user')
    op.drop_column('user', 'api_token')
    # ### end Alembic commands ###
